workflows:
  flutter-app:
    name: Flutter CI/CD Pipeline
    instance_type: mac_mini_m1 # 适用于 iOS 和 Android 的 macOS 构建机
    max_build_duration: 120
    environment:
      flutter: stable
      groups:
        - firebase_credentials # 在 Codemagic 设置环境变量

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true

    scripts:
      - name: 设置 Flutter 版本
        script: |
          flutter --version

      - name: 获取 Flutter 依赖
        script: |
          flutter pub get

      - name: 运行 Flutter 测试（可选）
        script: |
          flutter test

      - name: 构建 Android APK
        script: |
          flutter build apk --release

      - name: 构建 Android App Bundle
        script: |
          flutter build appbundle --release

      - name: 构建 iOS 应用
        script: |
          flutter build ios --no-codesign

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/ios/iphoneos/*.app

    publishing:
      firebase:
        firebase_service_account: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        android:
          app_id: 1:777480941037:android:927da45475270eeb1a4be4
          groups: adroid_testers

